# site settings
title: Akolade
subtitle: Tinubu
email: akolade.tinubu@gmail.com
description: >-
  I have strong passion for Autonomous Driving. I calm my nerves by watching a chess game :D
  On some days, I could be a joker telling funny relatable stories, or playing pranks.
  Oops, maybe I shouldn't have said that.
  Space travel? Let's go!
baseurl: ""
url: "https://aatinubu.github.io"

# contact info
author: Akolade Tinubu
street_address:
city:
state:
zip_code:
country:
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
twitter_username: aatinubu
linkedin_username: aatinubu
github_username: aatinubu
instagram_username: aatinubu

# Build settings
#theme: forty-jekyll-theme
plugins:
  - jekyll-feed

markdown: kramdown

sass:
  style: compressed
